version: "3"

services:
    api:
        build: .
        ports:
            - "3000":"3000"
        networks:
            - api_network

networks:
    api_network:
        driver: bridge
