version: "3.7"

services:
    api:
        build:
            context: .
            target: production
        ports:
            - "3000:3000"
        networks:
            - api_network
        environment: 
            - NODE_ENV=production
        env_file: 
            - ".env"
        command: npm run start
    api-dev:
        build:
            context: .
            target: development
        ports:
            - "3000:3000"
        networks:
            - api_network
        environment: 
            - NODE_ENV=development
        env_file: 
            - ".env"
        command: npm run dev
networks:
    api_network:
        driver: bridge
