version: "3"

services:
    api:
        build: .
        ports:
            - "3000:3000"
        networks:
            - api_network
        command: nodemon --exec babel-node ./src/bin/www --watch ./src
networks:
    api_network:
        driver: bridge
